# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='first_option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fourth_option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='right_option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='second_option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='third_option',
            field=models.TextField(),
        ),
    ]
