# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0003_auto_20171204_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatherQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='url',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='username',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='first_option',
            field=models.TextField(help_text='Insira aqui uma resposta alternativa (errada)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fourth_option',
            field=models.TextField(help_text='Insira aqui uma resposta alternativa (errada)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(help_text='Insira sua pergunta'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='right_option',
            field=models.TextField(help_text='Escreva aqui a resposta correta para a pergunta'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='second_option',
            field=models.TextField(help_text='Insira aqui uma resposta alternativa (errada)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='third_option',
            field=models.TextField(help_text='Insira aqui uma resposta alternativa (errada)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='fatherquiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizes.FatherQuiz'),
        ),
    ]
