# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0005_auto_20171219_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='fatherquiz',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nome do Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='first_option',
            field=models.TextField(verbose_name='Resposta Incorreta nº1'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fourth_option',
            field=models.TextField(verbose_name='Resposta Incorreta nº4'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='right_option',
            field=models.TextField(verbose_name='Resposta Correta'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='second_option',
            field=models.TextField(verbose_name='Resposta Incorreta nº2'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='third_option',
            field=models.TextField(verbose_name='Resposta Incorreta nº3'),
        ),
    ]
